# Generated by Django 5.2.9 on 2025-12-02 15:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origin', models.CharField(max_length=100)),
                ('destination', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Route',
                'verbose_name_plural': 'Routes',
                'unique_together': {('origin', 'destination')},
            },
        ),
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('airline', models.CharField(max_length=100)),
                ('plane_type', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('price', models.PositiveIntegerField(default=0)),
                ('seats_total', models.PositiveIntegerField(default=0)),
                ('seats_available', models.PositiveIntegerField(default=0)),
                ('cancel_penalty_percent', models.PositiveIntegerField(default=10)),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flights', to='flights.route')),
            ],
            options={
                'ordering': ['date', 'time'],
            },
        ),
    ]
